Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -25,9 +25,14 @@ jobs:
       - name: Rename JAR for Consistency
         run: mv target/*.jar target/bankapp.jar
 
-      - name: Build Docker Image
+            - name: Build Docker Image
         run: |
+          if [[ -z "${{ secrets.DOCKER_HUB_USERNAME }}" ]]; then
+            echo "ERROR: DOCKER_HUB_USERNAME secret is not set!"
+            exit 1
+          fi
           docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/bankapp:latest .
+
 
       - name: Log in to Docker Hub
         run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
